### ISSUE TITLE
write_videofile  

### ISSUE THREAD

**Issue by leiyaohui** [sumitbinnani/Detect-and-Track#7] opened 2019-03-08 01:42 UTC
Hello, I'm bothering you again. When I ran to clip. write_videofile (parsed_args. output_file, audio = False), something went wrong. Could you help me solve this problem?

40%|████      | 151/376 [00:36<00:54,  4.11it/s]WARNING:py.warnings:F:/tracking/Detect-and-Track-master\utils\box_utils.py:18: RuntimeWarning: invalid value encountered in true_divide
  return float(s_intsec) / (s_a + s_b - s_intsec)

WARNING:py.warnings:D:\Program Files\Anaconda3\envs\lei\lib\site-packages\numpy\core\_methods.py:29: RuntimeWarning: invalid value encountered in reduce
  return umr_minimum(a, axis, None, out, keepdims)

Thanks!

**Comment by leiyaohui** [comment] 2019-03-08 02:24
What happens when the program runs to 40% and never moves?

**Comment by sumitbinnani** [comment] 2019-03-13 22:10
Can you share the video file? I haven't yet encountered any similar issues.

**Comment by leiyaohui** [comment] 2019-03-15 07:04
It's a very simple video, and I tried a lot of videos, all running without moving at all.

[inputcar.zip](https://github.com/sumitbinnani/Detect-and-Track/files/2969788/inputcar.zip)

Thank you！

**Comment by sumitbinnani** [comment] 2019-03-16 21:04
I am not getting any errors for the file you have linked. The detection is poor due to the low quality of video though. You might have to retrain the model for better detection.

Coming to the pipeline being stuck, you may insert a few print statement in the `pipeline.py` to see which line is preventing the code from proceeding. Once you find that, let me know and I will try to see what is causing the issue.

**Comment by leiyaohui** [comment] 2019-03-19 11:39
Thank you for your reply.Running to this point  
 clip = clip1.fl_image(detect_and_track.pipeline)
 clip.write_videofile(parsed_args.output_file, audio=False) ，I get 'clip'
![1](https://user-images.githubusercontent.com/42469241/54603034-4aa25c80-4a7e-11e9-9564-343a75d5bf57.png)
I wonder if this is wrong.Thank you！

**Comment by sumitbinnani** [comment] 2019-03-19 23:49
This seems correct. Can you insert debug point inside `pipeline` here: https://github.com/sumitbinnani/Detect-and-Track/blob/master/pipeline/pipeline.py#L32

**Comment by leiyaohui** [comment] 2019-03-20 02:07
Thank you for your quick reply.I set the breakpoint and it seems that there was no mistake.

**Comment by sumitbinnani** [comment] 2019-03-21 21:15
Closing the issue then :-)

**Comment by sumitbinnani** [comment] 2019-03-21 22:20
Hey, this might be the cause of the issue:
https://github.com/sumitbinnani/Detect-and-Track/blob/master/utils/box_utils.py#L18

Insert this before the last statement:
```
if abs(s_a + s_b - s_intsec) <= 1e-7:
    return 0
```

**Comment by leiyaohui** [comment] 2019-03-26 12:59
Thank you very much! According to your suggestion, the final procedure runs, but I want to know why? Thank you again!

**Closed as completed** 2019-03-27 00:01 UTC

**Comment by sumitbinnani** [comment] 2019-08-08 21:01
Division by zero was the culprit!
